version: '3'

services:
  nginx:
    container_name: nginx
    networks:
    - inception
    build: requirements/nginx
    expose:                         
    - "9000"
    ports:
    - "443:443"
    volumes:
      - 'wp:/var/www/wordpress'
    depends_on:
      - wordpress
    restart: always
  wordpress:
    container_name: wordpress
    networks:
    - inception
    build: requirements/wordpress
    env_file:
      - .env
    volumes:
      - 'wp:/var/www/wordpress'
    depends_on:
      - mariadb
    restart: always
  mariadb:
    container_name: mariadb
    networks:
      - inception
    build: requirements/mariadb
    env_file:
      - .env
    volumes:
    - 'db:/var/www/db'
    restart: always
volumes:
  wp:
    driver: local
    driver_opts:
      type: 'none'
      device: '/home/lambrette/data/wp'
      o: 'bind'
  db:
    driver: local
    driver_opts:
      type: 'none'
      device: '/home/lambrette/data/db'
      o: 'bind'
networks:
  inception:
    driver: bridge