version: '3'

services:
  nginx:
    container_name: nginx
    networks:
    - inception
    build: requirements/nginx
    expose:                         
    - "9000"
    ports:
    - "443:443"

  wordpress:
    container_name: wordpress
    networks:
    - inception
    build: requirements/wordpress
    environment:
     - WORDPRESS_DB_PASSWORD=password
     - WORDPRESS_DB_USER=root
    volumes:
    - /home/abourdar/data

    